version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo "Build phase"

      - cd labs-src

      - ./prepare_source_for_labs.sh ./ai/text-analysis/www/script.js
      - zip -r ./aiml-workshops-text-analysis-www.zip ./ai/text-analysis/www
      - zip -r ./aiml-workshops-text-analysis-api.zip ./ai/text-analysis/api.py
artifacts:
  secondary-artifacts:
    WorkshopResourcesArtifact:
      files:
        - $CODEBUILD_SRC_DIR/labs-src/aiml-workshops-text-analysis-www.zip
      name: WorkshopResourcesArtifact
      discard-paths: yes
    WorkshopInfraArtifact:
      files:
        - $CODEBUILD_SRC_DIR/labs-src/aiml-workshops-text-analysis-api.zip
        - $CODEBUILD_SRC_DIR/labs-src/ai/text-analysis/aiml-workshops-text-analysis.template.yaml
      name: WorkshopInfraArtifact
      discard-paths: yes
